#!/usr/bin/env bash

if [[ ! -d $(xcode-select -p) ]]; then
  printf "XCode dev utilities not detected. Enter `xcode` to install: "

  read can_install_xcode

  if [[ "$can_install_xcode" == "xcode" ]]; then
    xcode-select --install
  else
    echo "Manual installation command: \e[36mxcode-select --install\e[0m"
  fi
fi

echo "Installing homebrew..."
which brew 2>&1 > /dev/null || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

echo "Installing oh-my-zsh..."
[[ ! -d "$HOME/.oh-my-zsh" ]] && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

brew install --cask alacritty
brew install tmux
brew install neovim
brew install ripgrep
brew install fd
brew install exa

brew tap solidiquis/tap
brew install erdtree
