#!/bin/bash

alias python="python3"
alias :q="exit"
alias vi="vim"

if [[ $OSTYPE =~ "darwin" ]]; then
  alias rustdoc="rustup doc --toolchain=stable-x86_64-apple-darwin"
fi

if [[ -f $(which exa) ]]; then
  alias ls="exa"
  alias l="exa -abghHliS"
fi

