#!/bin/bash

# Bookmark current working directory.
mkbm() {
  [[ -z "$1" ]] && \
    echo "Error: Provide a name for the bookmark." && \
    return 

  wd=$(pwd)

  [[ ! -f $HOME/.cache/bookmarks ]] && \
    echo "$1=$wd" > $HOME/.cache/bookmarks && \
    echo "$1 added." && \
    return

  while IFS= read -r line; do
    [[ $line =~ $1  ]] && echo "Bookmark $1 already exists." && return
  done < $HOME/.cache/bookmarks

  echo "$1=$wd" >> $HOME/.cache/bookmarks && echo "$1 added."
}

# Jump to bookmark.
jbm() {
  [[ ! -f $HOME/.cache/bookmarks ]] && \
    echo "You don't have any bookmarks yet." && \
    return

  [[ $SHELL == "/bin/zsh" ]] && setopt local_options BASH_REMATCH

  [[ -z "$1" ]] && \
    echo "Error: Provide a bookmark name." && \
    return 

  bookmarks=$(cat $HOME/.cache/bookmarks)

  [[ $bookmarks =~ ($1=[[:print:]]*) ]] && \
    [[ ${BASH_REMATCH[1]} =~ (=[[:print:]]*) ]] && \
    cd ${BASH_REMATCH[1]:1} && \
    return

  echo "Bookmark $1 does not exist."
}

# Remove a bookmark.
rmbm() {
  [[ ! -f $HOME/.cache/bookmarks ]] && \
    echo "You don't have any bookmarks yet." && \
    return

  [[ -z "$1" ]] && \
    echo "Error: Provide a bookmark name." && \
    return 

  arg="/^$1=.*/d"
  sed -i "" $arg $HOME/.cache/bookmarks
  echo "Bookmark $1 removed."
}

# List bookmarks.
lsbm() {
  [[ ! -f $HOME/.cache/bookmarks ]] && \
    echo "You don't have any bookmarks yet." && \
    return

  cat $HOME/.cache/bookmarks
}
