#!/bin/bash

# Initial tasks to run on window boot up.
run_init_tasks() {
  exec_tmux
  curwin
  vi_mode
}

# Info about current terminal window and other things.
curwin() {
  hline=""
  for i in {0..55}; do
    hline+="\u2500"
  done

  [[ $SHELL == "/bin/zsh" ]] && setopt local_options BASH_REMATCH

  num_cores=$(system_profiler SPHardwareDataType | grep Cores)
  num_cores=$([[ $num_cores =~ ([[:digit:]]+) ]] && echo ${BASH_REMATCH[1]})

  echo "\x1B[31m\u250C$hline\u2510\x1B[0m" 
  echo "\x1B[31m\u2502   ____              _ _ _       ____  _          _ _   \u2502\x1B[0m" 
  echo "\x1B[31m\u2502  | __ )  ___ _ __  (_|_| )___  / ___|| |__   ___| | |  \u2502\x1B[0m"
  echo "\x1B[31m\u2502  |  _ \ / _ \ '_ \ | | |// __| \___ \| '_ \ / _ \ | |  \u2502\x1B[0m"
  echo "\x1B[31m\u2502  | |_) |  __/ | | || | | \__ \  ___) | | | |  __/ | |  \u2502\x1B[0m"
  echo "\x1B[31m\u2502  |____/ \___|_| |_|/ |_| |___/ |____/|_| |_|\___|_|_|  \u2502\x1B[0m"
  echo "\x1B[31m\u2502                                                        \u2502\x1B[0m" 
  echo "\x1B[31m\u2514$hline\u2518\x1B[0m" 

  echo "\x1B[34m\u2192\x1B[0m User:        $(whoami)"
  echo "\x1B[34m\u2192\x1B[0m OS Type:     $OSTYPE"
  echo "\x1B[34m\u2192\x1B[0m Terminal:    $(tty) $(echo $$)"
  echo "\x1B[34m\u2192\x1B[0m Shell:       $SHELL"
  echo "\x1B[34m\u2192\x1B[0m Tmux:        $([ ! -z "$TMUX" ] && echo "\x1B[32mrunning...\x1B[0m" || echo "\x1B[31mnot found...\x1B[0m")"
  echo "\x1B[34m\u2192\x1B[0m Local IP:    $(locipdev)"
  echo "\x1B[34m\u2192\x1B[0m Total Cores: $num_cores"
  echo 
}

# Boot tmux if tmux exists and is not running.
exec_tmux() {
  which tmux &> /dev/null && \
    [ -n "$PS1" ] && \
    [[ ! "$TERM" =~ screen ]] && \
    [[ ! "$TERM" =~ tmux ]] && \
    [ -z "$TMUX" ] && \
    exec tmux
}

vi_mode() {
  set -o vi
}
