#!/bin/bash

# Local IP of device.
locipdev() {
  [[ "$OSTYPE" =~ "darwin" ]] && ipconfig getifaddr en0 && return
  hostname -I
}

# List bluetooth devices on mac.
btdevices() {
  [[ "$OSTYPE" =~ "darwin" ]] && system_profiler SPBluetoothDataType
}

# Copy working directory to clipboard.
cpwd() {
  pwd | pbcopy
}

vi() {
  if [ -f /usr/local/Cellar/vim/8.2.3000/bin/vim ]; then
    /usr/local/Cellar/vim/8.2.3000/bin/vim
  else
    vim
  fi
}

cr() {
  cargo run
}

ct() {
  cargo test
}

cursor_vis() {
  echo "\x1b[?25h"
}

printrgb() {
  printf "\x1b[38;2;$1;$2;$3m"
  printf "$4\n"
  printf "\x1b[0m"
}
