#!/bin/bash

locipdev() {
  [[ "$OSTYPE" =~ "darwin" ]] && ipconfig getifaddr en0 && return
  hostname -I
}

btdevices() {
  [[ "$OSTYPE" =~ "darwin" ]] && system_profiler SPBluetoothDataType
}

cpwd() {
  pwd | pbcopy
}

cursor_vis() {
  echo "\x1b[?25h"
}

printrgb() {
  printf "\x1b[38;2;$1;$2;$3m"
  printf "$4\n"
  printf "\x1b[0m"
}

sm() {
  if [[ $MODE == 'light' ]]; then
    awk '{sub(/light/,"dark")}1' $DOTFILES/zsh/mode >> /dev/null
    export MODE='dark'
    alac-pretty gruvbox_dark
  else
    awk '{sub(/dark/,"light")}1' $DOTFILES/zsh/mode >> /dev/null
    export MODE='light'
    alac-pretty gruvbox_light
  fi
}

s() {
  source $HOME/.zshrc
}

h() {
  history | grep $1
}

16col() {
  for i in {30..37}; do
    printf "$i \u2B62  \e[${i}m\u25C6\e[0m\n"
  done
}

256col() {
  for i in {0..255}; do
    printf "\e[38;5;${i}m${i}\e[0m "
  done
  
  printf "\n"
}
