#!/bin/bash

locipdev() {
  [[ "$OSTYPE" =~ "darwin" ]] && ipconfig getifaddr en0 && return
  hostname -I
}

btdevices() {
  [[ "$OSTYPE" =~ "darwin" ]] && system_profiler SPBluetoothDataType
}

cpwd() {
  pwd | pbcopy
}

cursor_vis() {
  echo "\x1b[?25h"
}

printrgb() {
  printf "\x1b[38;2;$1;$2;$3m"
  printf "$4\n"
  printf "\x1b[0m"
}

s() {
  source $HOME/.zshrc
}

h() {
  history | grep $1
}

16col() {
  for i in {30..37}; do
    printf "$i \u2B62  \e[${i}m\u25C6\e[0m\n"
  done
}

256col() {
  for i in {0..255}; do
    printf "\e[1;38;5;${i}m${i}\e[0m "
  done
  
  printf "\n"
}

j() {
  if [[ -z $BOOKMARKS ]]; then
    BOOKMARKS="$HOME/.cache/bookmarks"
  fi

  if [[ ! -f $BOOKMARKS ]]; then
    touch $BOOKMARKS
  fi

  case $1 in

    -l)
      cat $BOOKMARKS
      ;;

    -c)
      bookmark="${2}=$(pwd)"
      echo $bookmark >> $BOOKMARKS
      echo $bookmark
      ;;

    -d)
      pat="/^$2=.*/d"
      sed -i "" $pat $BOOKMARKS
      cat $BOOKMARKS
      ;;

    -w)
      cat $BOOKMARKS
      echo "" > $BOOKMARKS
      ;;

    *)
      [[ $SHELL == "/bin/zsh" ]] && setopt local_options BASH_REMATCH
      bookmarks=$(cat $BOOKMARKS)

      if [[ $bookmarks =~ ($1=[[:print:]]*) ]]; then
        [[ ${BASH_REMATCH[1]} =~ (=[[:print:]]*) ]] && cd ${BASH_REMATCH[1]:1}
      fi
      ;;
  esac
}
